# Read input
start, end = map(int, input().split())

class CyclicCounter:
    def __init__(self, start, end):
        self.start = start
        self.end = end
        self.current = start

    def __iter__(self):
        return self

    # TODO: Implement the __next__() method
    def __next__(self):
        result = self.current
        self.current += 1
        if self.current > self.end:
            self.current=self.start
        return result
      
        


# Create an instance of CyclicCounter
counter = CyclicCounter(start, end)

# TODO: Use a loop to print the first 10 numbers generated by the iterator
for i in range(10):
    print(next(counter))
# Remember to print each number on a new line

